### ISSUE TITLE
Swiss Franc separator doesn't work under new Android versions

### ISSUE THREAD

**Issue by jpjpjp28** [BlacKCaT27/CurrencyEditText#23]
I tested it under ICS and it works but when I tested it under marshmallow, it doesn't work. It just shows space.

**Comment by BlacKCaT27** [comment]
First, I apologize for the huge delay in my response. I'm just now revisiting this library and am working to address the open issues. 

Could you give more detail on what you're seeing? In my testing with "CH" locale I'm not seeing an issue with the separators; I see ',' and '.' where expected.

What I AM seeing, at least on my 7.1 device, is that there's a missing space between "CHF" and the formatted value. 

However, in my unit tests run locally on my PC, that issue does not appear and I see "CHR <value>" with the proper spacing. This leads me to believe the bug is actually within Androids java distribution, and not this library or the Currency/Locale libraries of Java itself.

**Comment by BlacKCaT27** [comment]
My initial response was incorrect due to a bug I've since fixed.

However, I don't see any issue with spacing or separators with swiss francs in the latest version. Please try v2.0 and if you still have trouble, reopen the issue.
