### ISSUE TITLE
CurrencyTextView

### ISSUE THREAD

**Issue by aandis** [BlacKCaT27/CurrencyEditText#26]
Is there a `TextView` exposed by this lib which handles all currency related functionalities just like the `EditText` does? I am looking to display currency stored in `long` in a `TextView`.

**Comment by BlacKCaT27** [comment]
Hello!

No, not directly. But what you can do is use the
CurrencyTextFormatter.FormatText() method to format the value you want,
then put it into a TextView yourself.

**Comment by aandis** [comment]
Thanks, got it working. Would you be open to accepting a pr for this if I made one? I think it could be a useful feature in this lib.

**Comment by BlacKCaT27** [comment]
I'll certainly consider it. I agree it's handy, but it's also pretty
straightforward to do on your own since we expose the formatter, and I'm
not sure about adding additional code to maintain for something that isn't
core to the original intent of the library. Not just the code of populating
a TextView, but also ensuring the formatter plays nice with various fonts,
scales, etc.

But I'll certainly mull it over. If you do submit a PR, please include unit
tests covering any new code, and perhaps add one of the new TextViews to
the test app so there's an example handy. I'll handle updating the readme
if I end up accepting it.

Glad the library was able to help you out, regardless!


On Mar 12, 2017 1:09 PM, "Abhishek" <notifications@github.com> wrote:

Thanks, got it working. Would you be open to accepting a pr for this if I
made one? I think it could be a useful feature in this lib.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/BlacKCaT27/CurrencyEditText/issues/26#issuecomment-285958582>,
or mute the thread

**Comment by BlacKCaT27** [comment]
After further consideration, I don't think this is necessarily an appropriate addition to this library specifically. If you wish to make a second library which depends on this one for formatting, by all means.
