### ISSUE TITLE
Is it possible to relies on currency code without Locale?

### ISSUE THREAD

**Issue by b95505017** [BlacKCaT27/CurrencyEditText#42]
As title.
In our project, we init the `Currency` object by currency code instead of `Locale`.

**Comment by BlacKCaT27** [comment]
No. Overriding the defaults based on currency was supported before, but was
removed in 2.0 due to a lot of extra complexity it added for very little
net gain.

If you're starting from a currency object instead of locale, you can use
NumberFormat to do a "lookup" of sorts to find the matching locale object.

https://coderanch.com/t/609799/java/locale-instance-currency-symbol-java
