### ISSUE TITLE
NumberFormatException for number greater than Long max value

### ISSUE THREAD

**Issue by benwicks** [BlacKCaT27/CurrencyEditText#43]
```
java.lang.NumberFormatException: For input string: "10000000000000000000"
    at java.lang.Long.parseLong(Long.java:593)
    at java.lang.Long.valueOf(Long.java:804)
    at com.blackcat.currencyedittext.CurrencyTextWatcher.afterTextChanged(CurrencyTextWatcher.java:49)```

**Comment by BlacKCaT27** [comment]
Is there something specific you'd like to see otherwise?

I could wrap it in a library-specific exception, but all that would do is
hide/wrap the actual error. I don't plan on supporting something akin to
BigInt or anything like that. If you're working with values outside the
range of Long.MaxValue, you may have to do some mishmashing of the number
yourself to get it to place nicely with the formatter.

**Comment by benwicks** [comment]
What do you think about just catching the exception and ignoring any input that fails the `Long.valueOf` call?

**Comment by BlacKCaT27** [comment]
Having spent the last two weeks at work stuck in javascript hell, I think
that silently failing is the bane of all development and anything that
fails should fail as loud and as fast as possible. I'm fine with an
end-user seeing the occasional error/crash if it means developers are far
more likely to see bugs before launching to begin with.

**Comment by benwicks** [comment]
👍 That makes sense. Thanks for the quick responses!
